const ACTION_TYPES = {
  GET_TODOS: "GET_TODOS",
  CREATE_TODO: "CREATE_TODO",
  DELETE_TODO: "DELETE_TODO",
  FINISH_TODO: "FINISH_TODO",
  UPDATE_TODO: "UPDATE_TODO"
};
export default ACTION_TYPES;
